### PR TITLE
Fixing service transmitter failing synchronization

### PR DESCRIPTION
**Pull request by jakubjezek001**
## Solving following bug:
- **Service Transmitter**: 
	- creation of Asset in AYON was resolving in duplicity of Asset entities on ShotGrid server
	- Assets are now correctly typed in ShotGrid and inherits AssetCategory name from AYON

- **Service Processor**: 
	- Synchronization of project from AYON to ShotGrid was causing duplicating of Assets 
	- Assets are now correctly typed in ShotGrid and inherits AssetCategory name from AYON

## Aditional notes:
- workflow is currently locked on parent folder for assets to be AssetCategory folder type. The name of the parent is then used for defining `sg_asset_type` entity field.
- methods in Shotgrid common module were type annotated
- some typos were fixed but not all of it (there is still a log to be fixed) 
- version was bumped to `0.4.2-dev.3`

currently the PR is based on latest changes form https://github.com/ynput/ayon-shotgrid/pull/99

closes https://github.com/ynput/ayon-shotgrid/issues/98
closes https://github.com/ynput/ayon-shotgrid/issues/90

### CODE REVIEW

**Comment by tweak-wtf** [comment]
i'm just testing this out a bit.
now i get the following stacktrace:
```
ERROR: Unable to create SG entity Asset with data: {'sg_asset_type': 'Assets', 'project': {'type': 'Project', 'id': 5172, 'code': 'aas01', 'name': 'ay_aq_sg_01', 'sg_status': '01 Pitch', 'sg_ayon_auto_sync': False, 'tags': []}, 'code': 'rndasset', 'sg_ayon_id': 'a0274cc0143f11efa3e7bb441d060570', 'sg_ayon_sync_status': 'Synced'}
```

i have a suspicion that it uses the item's parent name (in this case `sg_asset_type = 'Assets'`) instead of the item's type.
i do have `rndasset` structured underneath an `Assets` folder

**Comment by jakubjezek001** [comment]
> i have a suspicion that it uses the item's parent name (in this case `sg_asset_type = 'Assets'`) instead of the item's type.
> i do have `rndasset` structured underneath an `Assets` folder

Yes that is correct. So your structure is following, and we will need to enhance the workflow, so we are able to do this.

```
ProjectX
   +-Assets(Folder:Folder)
        +-rndasset
```
Yes I am actually converting the parent name into the sg_asset_type. Because the integration from SG to AY is converting sg asset type into parent folder AsssetCategory so in AYON all assets are grouped by categories. Those are inherited from the way SG is dealing with type grouping.

Following is the expected structure.
```
ProjectX
   +-Vehicle(Folder:AssetCategory)
        +-rndasset
```

**Comment by tweak-wtf** [comment]
alrighty... i'll change up my project structure to comply with this apporach and report back ✌️

**Comment by tweak-wtf** [comment]
> alrighty... i'll change up my project structure to comply with this apporach and report back ✌️

I can confirm that Shots ind general and Assets when naming the parent folder of the asset after your Pipeline Step are being correctly synced to SG.
I also don't get any duplicates anymore when re-syncing AY->SG

**Review by MilaKudr — APPROVED** [review]

**Pull request merged**
